export const SHOW_SCREEN = "SHOW_SCREEN"
export const RESIZE_SCREEN = "RESIZE_SCREEN"
export const PAUSE_SET = "PAUSE_SET"

export const MOUSE_SET = "MOUSE_SET"

export const UPDATE_BODIES = "UPDATE_BODIES"
export const UPDATE_BOARD = "UPDATE_BOARD"
export const UPDATE_TILE = "UPDATE_TILE"
export const UPDATE_PAGE = "UPDATE_PAGE"

export const UI_SHOW = "UI_SHOW"

export const SPELLBOOK_SHOW = "SPELLBOOK_SHOW"
export const SPELLBOOK_LENGTH_SET = "SPELLBOOK_LENGTH_SET"
export const SPELLBOOK_LOAD = "SPELLBOOK_LOAD"

export const BATTLE_SHOW = "BATTLE_SHOW"
export const BATTLE_CLEAR = "BATTLE_CLEAR"
export const BATTLE_SPELL_TITLE_SHOW = "BATTLE_SPELL_TITLE_SHOW"
export const BATTLE_SPELL_TITLE_SET = "BATTLE_SPELL_TITLE_SET"
export const BATTLE_START_SHOW = "BATTLE_START_SHOW"
export const BATTLE_MENU_SHOW = "BATTLE_MENU_SHOW"
export const BATTLE_PHASE_FORCE_NEXT = "BATTLE_PHASE_FORCE_NEXT"
export const BATTLE_RESULT_SET = "BATTLE_RESULT_SET"

export const PLAYER_ANGLE_SET = "PLAYER_ANGLE_SET"
export const PLAYER_HP_SET = "PLAYER_HP_SET"
export const PLAYER_MAXHP_SET = "PLAYER_MAXHP_SET"
export const PLAYER_POSITION_SET = "PLAYER_POSITION_SET"
export const PLAYER_MOVED_SET = "PLAYER_MOVED_SET"

export const MOVE_SHOW = "MOVE_SHOW"

export const CHAT_SHOW = "CHAT_SHOW"
export const CHAT_MESSAGES_SET = "CHAT_MESSAGES_SET"

export const SCENARIO_SHOW = "SCENARIO_SHOW"
export const START_BUTTON_SHOW = "START_BUTTON_SHOW"
export const FIGHT_ENTRY_UPDATE = "FIGHT_ENTRY_UPDATE"
